### ISSUE TITLE
报错：AttributeError: module 'signal' has no attribute 'SIGUSR1'

### ISSUE THREAD

**Issue by qq4199** [Ran-Xing/WZRY_AirtestIDE#1]
![image](https://github.com/XRSec/WZRY_AirtestIDE/assets/40818706/aa108183-727c-43e5-a3f4-27330ae629b8)
大哥，这个报错用什么替代啊

**Comment by Ran-Xing** [comment]
😓，你只是python什么版本

**Comment by qq4199** [comment]
python3.8.4

> 😓，你只是python什么版本

**Comment by qq4199** [comment]
>python3.8.4
> 
> > 😓，你只是python什么版本

**Comment by Ran-Xing** [comment]
好哥哥百度下吧
